function [fitresult, gof] = createFit(dist, v)
%CREATEFIT(DIST,V)
%  Create a fit.
%
%  Data for 'Wheel velocity' fit:
%      X Input: dist
%      Y Output: v
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 09-May-2023 17:35:16


%% Fit: 'Wheel velocity'.
[xData, yData] = prepareCurveData( dist, v );

% Set up fittype and options.
ft = fittype( 'exp2' );
opts = fitoptions( 'Method', 'NonlinearLeastSquares' );
opts.Display = 'Off';
opts.Normalize = 'on';
opts.Robust = 'Bisquare';
opts.StartPoint = [2793.39441851214;-0.161015411051406;-1201.18884687413;-0.667177938883837];

% Fit model to data.
[fitresult, gof] = fit( xData, yData, ft, opts );

% Plot fit with data.
figure( 'Name', 'Wheel velocity' );
h = plot( fitresult, xData, yData );
legend( h, 'v vs. dist', 'Wheel velocity', 'Location', 'NorthEast', 'Interpreter', 'none' );
% Label axes
xlabel( 'dist', 'Interpreter', 'none' );
ylabel( 'v', 'Interpreter', 'none' );
grid on


